Feature: The Apple website
  Background:
    Given I am in "https://www.apple.com/"
    When I click the button/link "#ac-ls-close"
    Then the url should have "apple"

  Scenario: Purchase a MacBook Air
    When I click the button/link "//*[@data-analytics-title='mac']"
    Then the url should have "mac"
    When I click the button/link ".chapternav-link"
    And I click the button/link ".chapternav-link"
    And I click the button/link "//*[@data-analytics-title='buy']"
    Then the url should have "buy-mac"
    When I click the button/link "//*[@data-autom='filterButton-m2']"
    Then the url should have "m2"
    When I scroll to "//*[@data-autom='proceed-13inch-best']"
    And I click the button/link "//*[@data-autom='proceed-13inch-best']"
    And I scroll to "//*[@data-autom='optionSelector-memory_3']"
    And I click the button/link "//*[@data-autom='optionSelector-memory_3']"
    And I scroll to "//*[@data-autom='optionSelector-hard_drive_3']"
    And I click the button/link "//*[@data-autom='optionSelector-hard_drive_3']"
    And I scroll to "//*[@data-autom='optionSelector-adaptersremotes_2']"
    And I click the button/link "//*[@data-autom='optionSelector-adaptersremotes_2']"
    And I scroll to "//*[@data-autom='optionSelector-software_2']"
    And I click the button/link "//*[@data-autom='optionSelector-software_2']"
    And I click the button/link "//*[@data-autom='addToCart']"
    Then there should be a/an "button" with content "Review Bag"

  Scenario: Purchase an iPad Pro
    When I click the button/link "//*[@data-analytics-title='ipad']"
    Then the url should have "ipad"
    When I click the button/link ".chapternav-link"
    And I click the button/link "//*[@data-analytics-title='buy - ipad pro']"
    Then the url should have "buy-ipad"
    When I click the button/link "//*[@data-autom='dimensionScreensize12_9inch']"
    And I click the button/link "//*[@data-autom='dimensionColorspace_gray']"
    And I click the button/link "//*[@data-autom='dimensionCapacity2tb']"
    And I click the button/link "//*[@data-autom='dimensionConnectionwifi']"
    And I click the button/link "//*[@data-autom='noEngraving-app']"
    And I click the button/link "//*[@data-autom='acc_pencil_grp_add']"
    And I click the button/link "//*[@data-autom='acc_magickeyboard_12_9inch_add']"
    And I click the button/link "//*[@data-autom='add-to-cart']"
    Then there should be a/an "button" with content "Review Bag"

  Scenario: Purchase an Apple TV
    When I click the button/link "//*[@data-analytics-title='tv and home']"
    Then the url should have "tv-home"
    When I click the button/link ".chapternav-link"
    And I click the button/link "//*[@data-analytics-title='order now - apple tv 4k']"
    Then the url should have "buy-tv"
    When I click the button/link "//*[@data-autom='dimensionConnectionwifiethernettv128gb']"
    And I click the button/link "//*[@data-autom='add-to-cart']"
    Then there should be a/an "button" with content "Review Bag"